### PR TITLE
Implement Htmlable to allow use of escaped Blade tags ({{ $var }})

### PR DESCRIPTION
**Pull request by mikemand**
Allows users to use `{{ Notification::all() }}` instead of having to manually call `toHTML()` and output using unescaped Blade tags. (`{!! Notification::all()->toHTML() !!}`)

This, unfortunately, increases the dependency of `illuminate/support` to a minimum of `5.1.3`, since that is when `Htmlable` was added. (https://github.com/laravel/framework/pull/9271)

There is also now a cap on the dependency to `<5.3` just in case they change `Htmlable` with the 5.3 release.

(P.S.: This is my last PR today, I promise! Unless there is some kind of error with this, then I'll PR a fix.)

### CODE REVIEW

**Comment by garf** [comment]
Thank you for your PR.
Do you mind also to update the documentation?

**Comment by mikemand** [comment]
Not at all! Will do so now. Do you want me to do the Russian documentation as well, or will you handle that?

**Comment by garf** [comment]
I can handle it.
Also please be sure to pull from master.
I made some updates.

**Comment by mikemand** [comment]
I tried to rebase my branch on master, but I couldn't push the changes without a force push (which I'm not sure what would have happened with the PR then), so I ran a normal fetch + merge.

I've changed the installation instructions as well as update the render docs.

**Comment by garf** [comment]
Thank you. Merged.

**Comment by mikemand** [comment]
Not a problem, thank you. :)

**Pull request merged**
